name: Python package

on: [push]

jobs:
  build:

    runs-on: ${{matrix.os}} 
    strategy:
      matrix:
        os : [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with Pylint
        run: |
          pylint $(git ls-files '*.py');
      - name: Test with pytest
        run: |
          pytest
